version: '3'

services:
  frontend:
    build: ./frontend
    restart: always
    container_name: frontend
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./frontend:/app
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
  api:
    build: ./server
    restart: always
    container_name: api
    ports:
      - '4444:4444'
    volumes:
      - /app/node_modules
      - ./server:/app
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
  postgres:
    image: postgres
    restart: always
    container_name: DB
    environment:
      POSTGRES_PASSWORD: moneyadmin
      POSTGRES_USER: admin
      POSTGRES_DB: money_tracker
    healthcheck:
      test: pg_isready -h localhost -U $$POSTGRES_USER
      interval: 5s
      timeout: 10s
      retries: 120
    volumes:
      - pg_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - '8888:8080'
volumes:
  pg_data: